import '../models/product.dart';

class ProductRepository {
  ProductRepository._();

  static final List<Product> _products = [
    Product(
      name: 'iPhone 15 Pro',
      slug: 'iphone-15-pro',
      description:
          'Latest iPhone with A17 Pro chip, titanium design, and pro camera system.',
      storeId: 'store-1',
      storeName: 'Apple Store',
      category: 'Phones',
      subcategory: 'Smartphones',
      brand: 'Apple',
      price: 120000,
      oldPrice: 150000,
      currency: 'KES',
      images: [],
      thumbnail:
          'https://images.unsplash.com/photo-1556656793-08538906a9f8?w=500',
      sku: 'IPHONE-15-PRO',
      rating: 4.8,
      reviewsCount: 1250,
      soldCount: 3500,
      status: ProductStatus.active,
      isFeatured: true,
      isFlashSale: true,
      flashSaleEnd: DateTime.now().add(const Duration(hours: 6)),
      flashSaleStock: 50,
      freeShipping: true,
      isNewArrival: false,
      isBestSeller: true,
      tags: ['smartphone', 'apple', 'iphone', 'premium'],
      specifications: {
        'Display': '6.1" Super Retina XDR OLED',
        'Processor': 'A17 Pro',
        'Storage': '256GB',
        'RAM': '8GB',
        'Camera': '48MP Main + 12MP Ultrawide + 12MP Telephoto',
        'Battery': '3274mAh',
        'OS': 'iOS 17',
      },
      variants: [
        {'color': 'Natural Titanium', 'price': 120000},
        {'color': 'Blue Titanium', 'price': 120000},
        {'color': 'White Titanium', 'price': 120000},
      ],
      stock: 150,
      condition: ProductCondition.newCondition,
      weight: 0.206,
      dimensions: '146.6 x 70.6 x 8.25 mm',
    ),
    Product(
      name: 'Sony WH-1000XM5 Headphones',
      slug: 'sony-wh1000xm5',
      description:
          'Premium noise-cancelling headphones with industry-leading ANC and exceptional sound quality.',
      storeId: 'store-2',
      storeName: 'Electronics Hub',
      category: 'Electronics',
      subcategory: 'Audio',
      brand: 'Sony',
      price: 45000,
      oldPrice: 55000,
      currency: 'KES',
      images: [],
      thumbnail:
          'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=500',
      sku: 'SONY-WH-1000XM5',
      rating: 4.7,
      reviewsCount: 890,
      soldCount: 2100,
      status: ProductStatus.active,
      isFeatured: true,
      isNewArrival: true,
      freeShipping: true,
      isBestSeller: false,
      tags: ['headphones', 'sony', 'noise-cancelling', 'audio'],
      specifications: {
        'Driver Size': '30mm',
        'Frequency Response': '4Hz - 40kHz',
        'Noise Cancellation': 'Adaptive ANC',
        'Battery Life': '30 hours',
        'Weight': '250g',
      },
      variants: [
        {'color': 'Black', 'price': 45000},
        {'color': 'Silver', 'price': 45000},
        {'color': 'Midnight Blue', 'price': 47000},
      ],
      stock: 80,
      condition: ProductCondition.newCondition,
      weight: 0.250,
      dimensions: '',
    ),
    Product(
      name: 'Nike Air Max 90',
      slug: 'nike-air-max-90',
      description:
          'Classic sneakers with excellent comfort and iconic Air Max cushioning.',
      storeId: 'store-3',
      storeName: 'Fashion Store',
      category: 'Shoes',
      subcategory: 'Sneakers',
      brand: 'Nike',
      price: 12000,
      oldPrice: 15000,
      currency: 'KES',
      images: [],
      thumbnail:
          'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=500',
      sku: 'NIKE-AIR-MAX-90',
      rating: 4.6,
      reviewsCount: 2100,
      soldCount: 8900,
      status: ProductStatus.active,
      isFeatured: true,
      isBestSeller: true,
      freeShipping: false,
      tags: ['sneakers', 'nike', 'shoes', 'classic'],
      specifications: {
        'Upper': 'Leather and Mesh',
        'Sole': 'Rubber',
        'Cushioning': 'Air Max unit',
        'Closure': 'Lace-up',
      },
      variants: [
        {'color': 'White/Red', 'price': 12000},
        {'color': 'Black/Grey', 'price': 12000},
        {'color': 'Blue/White', 'price': 12500},
      ],
      stock: 200,
      condition: ProductCondition.newCondition,
      weight: 0.400,
      dimensions: '',
    ),
    Product(
      name: 'MacBook Pro 16"',
      slug: 'macbook-pro-16',
      description:
          'Powerful laptop for professionals with M3 Pro chip and stunning Liquid Retina XDR display.',
      storeId: 'store-1',
      storeName: 'Apple Store',
      category: 'Computers',
      subcategory: 'Laptops',
      brand: 'Apple',
      price: 280000,
      oldPrice: 320000,
      currency: 'KES',
      images: [],
      thumbnail:
          'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=500',
      sku: 'MACBOOK-PRO-16',
      rating: 4.9,
      reviewsCount: 450,
      soldCount: 950,
      status: ProductStatus.active,
      isFeatured: true,
      freeShipping: true,
      isBestSeller: true,
      tags: ['laptop', 'apple', 'macbook', 'professional'],
      specifications: {
        'Processor': 'M3 Pro',
        'RAM': '18GB Unified Memory',
        'Storage': '512GB SSD',
        'Display': '16.2" Liquid Retina XDR',
        'Battery': 'Up to 22 hours',
        'Ports': '3x Thunderbolt 4, HDMI, SDXC',
      },
      variants: [
        {'config': 'M3 Pro 18GB/512GB', 'price': 280000},
        {'config': 'M3 Pro 36GB/1TB', 'price': 350000},
        {'config': 'M3 Max 48GB/1TB', 'price': 420000},
      ],
      stock: 40,
      condition: ProductCondition.newCondition,
      weight: 2.14,
      dimensions: '35.57 x 24.81 x 1.68 cm',
    ),
    Product(
      name: 'Premium Wireless Headphones',
      slug: 'premium-wireless-headphones',
      description:
          'Experience superior sound quality with our premium wireless headphones. Featuring active noise cancellation, 30-hour battery life, and premium comfort design.',
      storeId: 'store-4',
      storeName: 'Electronics Pro',
      category: 'Electronics',
      subcategory: 'Audio',
      brand: 'AudioMax',
      price: 45000,
      oldPrice: 60000,
      currency: 'KES',
      images: [],
      thumbnail:
          'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=500',
      sku: 'AUDIO-MAX-001',
      rating: 4.8,
      reviewsCount: 1250,
      soldCount: 3500,
      status: ProductStatus.active,
      isFeatured: true,
      isFlashSale: true,
      flashSaleEnd: DateTime.now().add(const Duration(hours: 6)),
      flashSaleStock: 30,
      freeShipping: true,
      isBestSeller: true,
      tags: ['headphones', 'wireless', 'audio', 'premium'],
      specifications: {
        'Driver Size': '40mm',
        'Frequency Response': '20Hz - 20kHz',
        'Impedance': '32 Ohm',
        'Weight': '250g',
        'Battery Life': '30 hours',
        'Bluetooth': '5.3',
      },
      variants: [
        {'color': 'Matte Black', 'price': 45000},
        {'color': 'Pearl White', 'price': 45000},
        {'color': 'Rose Gold', 'price': 47000},
      ],
      stock: 60,
      condition: ProductCondition.newCondition,
      weight: 0.250,
      dimensions: '',
    ),
    Product(
      name: 'Samsung Galaxy S24 Ultra',
      slug: 'samsung-galaxy-s24-ultra',
      description:
          'Samsung flagship smartphone with Galaxy AI, S Pen, and 200MP camera.',
      storeId: 'store-5',
      storeName: 'Samsung Store',
      category: 'Phones',
      subcategory: 'Smartphones',
      brand: 'Samsung',
      price: 135000,
      oldPrice: 160000,
      currency: 'KES',
      images: [],
      thumbnail:
          'https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=500',
      sku: 'SAMSUNG-S24-ULTRA',
      rating: 4.7,
      reviewsCount: 980,
      soldCount: 2800,
      status: ProductStatus.active,
      isFeatured: true,
      isFlashSale: true,
      flashSaleEnd: DateTime.now().add(const Duration(hours: 6)),
      flashSaleStock: 25,
      freeShipping: true,
      isNewArrival: true,
      isBestSeller: true,
      tags: ['smartphone', 'samsung', 'galaxy', 'premium'],
      specifications: {
        'Display': '6.8" Dynamic AMOLED 2X',
        'Processor': 'Snapdragon 8 Gen 3',
        'Storage': '256GB',
        'RAM': '12GB',
        'Camera': '200MP + 50MP + 12MP + 10MP',
        'Battery': '5000mAh',
        'S Pen': 'Built-in',
      },
      variants: [
        {'color': 'Titanium Gray', 'price': 135000},
        {'color': 'Titanium Violet', 'price': 135000},
        {'color': 'Titanium Black', 'price': 135000},
      ],
      stock: 100,
      condition: ProductCondition.newCondition,
      weight: 0.233,
      dimensions: '162.3 x 79.0 x 8.6 mm',
    ),
    Product(
      name: 'PlayStation 5',
      slug: 'playstation-5',
      description:
          'Next-gen gaming console with lightning-fast loading, haptic feedback, and stunning 4K graphics.',
      storeId: 'store-6',
      storeName: 'Game World',
      category: 'Gaming',
      subcategory: 'Consoles',
      brand: 'Sony',
      price: 65000,
      oldPrice: 75000,
      currency: 'KES',
      images: [],
      thumbnail:
          'https://images.unsplash.com/photo-1606813907291-d86efa9b94db?w=500',
      sku: 'PS5-DISC-001',
      rating: 4.9,
      reviewsCount: 3200,
      soldCount: 15000,
      status: ProductStatus.active,
      isFeatured: true,
      isBestSeller: true,
      freeShipping: true,
      tags: ['gaming', 'playstation', 'sony', 'console'],
      specifications: {
        'CPU': 'AMD Zen 2 8-core @ 3.5GHz',
        'GPU': 'AMD RDNA 2 10.28 TFLOPS',
        'Memory': '16GB GDDR6',
        'Storage': '825GB SSD',
        'Resolution': 'Up to 8K',
        'Optical Drive': '4K Blu-ray',
      },
      variants: [
        {'edition': 'Standard', 'price': 65000},
        {'edition': 'Digital Edition', 'price': 55000},
      ],
      stock: 35,
      condition: ProductCondition.newCondition,
      weight: 4.5,
      dimensions: '39.0 x 26.0 x 10.4 cm',
    ),
    Product(
      name: 'AirPods Pro 2',
      slug: 'airpods-pro-2',
      description:
          'Adaptive audio, active noise cancellation, and personalised spatial audio.',
      storeId: 'store-1',
      storeName: 'Apple Store',
      category: 'Electronics',
      subcategory: 'Audio',
      brand: 'Apple',
      price: 32000,
      oldPrice: 38000,
      currency: 'KES',
      images: [],
      thumbnail:
          'https://images.unsplash.com/photo-1600294037681-c80b4cb5c22c?w=500',
      sku: 'AIRPODS-PRO-2',
      rating: 4.8,
      reviewsCount: 4100,
      soldCount: 22000,
      status: ProductStatus.active,
      isFlashSale: true,
      flashSaleEnd: DateTime.now().add(const Duration(hours: 6)),
      flashSaleStock: 40,
      freeShipping: true,
      isNewArrival: true,
      isBestSeller: true,
      tags: ['earphones', 'apple', 'airpods', 'wireless'],
      specifications: {
        'Chip': 'Apple H2',
        'ANC': 'Active Noise Cancellation',
        'Water Resistance': 'IPX4',
        'Battery Life': '6 hours (30h with case)',
        'Charging': 'MagSafe, Qi, USB-C',
      },
      variants: [
        {'model': 'USB-C', 'price': 32000},
        {'model': 'Lightning', 'price': 30000},
      ],
      stock: 120,
      condition: ProductCondition.newCondition,
      weight: 0.053,
      dimensions: '30.9 x 21.8 x 24.0 mm',
    ),
    Product(
      name: 'Logitech MX Mechanical',
      slug: 'logitech-mx-mechanical',
      description:
          'Premium mechanical keyboard with wireless connectivity and smart backlighting.',
      storeId: 'store-7',
      storeName: 'Tech Gear',
      category: 'Computers',
      subcategory: 'Accessories',
      brand: 'Logitech',
      price: 18000,
      currency: 'KES',
      images: [],
      thumbnail:
          'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=500',
      sku: 'LOGITECH-MX-MECH',
      rating: 4.6,
      reviewsCount: 560,
      soldCount: 1800,
      status: ProductStatus.active,
      isFeatured: true,
      freeShipping: false,
      tags: ['keyboard', 'logitech', 'mechanical', 'wireless'],
      specifications: {
        'Switch Type': 'Tactile Quiet',
        'Connectivity': 'Bluetooth + USB-C',
        'Battery Life': '15 days (backlit)',
        'Layout': 'Full-size',
        'Compatibility': 'Windows, macOS, Linux',
      },
      variants: [
        {'switch': 'Tactile Quiet', 'price': 18000},
        {'switch': 'Linear', 'price': 18000},
        {'switch': 'Clicky', 'price': 18500},
      ],
      stock: 65,
      condition: ProductCondition.newCondition,
      weight: 0.820,
      dimensions: '43.3 x 13.2 x 3.8 cm',
    ),
    Product(
      name: 'Apple Watch Series 9',
      slug: 'apple-watch-series-9',
      description:
          'Advanced health features, S9 SiP chip, and stunning always-on Retina display.',
      storeId: 'store-1',
      storeName: 'Apple Store',
      category: 'Electronics',
      subcategory: 'Wearables',
      brand: 'Apple',
      price: 55000,
      oldPrice: 65000,
      currency: 'KES',
      images: [],
      thumbnail:
          'https://images.unsplash.com/photo-1546868871-af0de0ae72ef?w=500',
      sku: 'APPLE-WATCH-S9',
      rating: 4.7,
      reviewsCount: 1800,
      soldCount: 6200,
      status: ProductStatus.active,
      isFlashSale: true,
      flashSaleEnd: DateTime.now().add(const Duration(hours: 6)),
      flashSaleStock: 20,
      freeShipping: true,
      isNewArrival: true,
      isBestSeller: true,
      tags: ['watch', 'apple', 'wearable', 'fitness'],
      specifications: {
        'Chip': 'S9 SiP',
        'Display': 'Always-On Retina LTPO OLED',
        'Health': 'Blood Oxygen, ECG, Temperature',
        'Water Resistance': 'WR50 (50m)',
        'Battery': 'Up to 18 hours',
        'OS': 'watchOS 10',
      },
      variants: [
        {'size': '41mm', 'price': 55000},
        {'size': '45mm', 'price': 59000},
      ],
      stock: 45,
      condition: ProductCondition.newCondition,
      weight: 0.042,
      dimensions: '45 x 38 x 10.7 mm',
    ),
  ];

  static List<Product> getAll() => List.unmodifiable(_products);

  static Product? getById(String id) {
    try {
      return _products.firstWhere((p) => p.slug == id);
    } catch (_) {
      return null;
    }
  }

  static List<Product> getByCategory(String categorySlug) {
    return _products
        .where((p) => p.category.toLowerCase() == categorySlug.toLowerCase())
        .toList();
  }

  static List<Product> search(String query) {
    if (query.isEmpty) return List.unmodifiable(_products);
    final q = query.toLowerCase();
    return _products
        .where(
          (p) =>
              p.name.toLowerCase().contains(q) ||
              p.description.toLowerCase().contains(q),
        )
        .toList();
  }

  static List<Product> getFeatured() =>
      _products.where((p) => p.isFeatured).toList();

  static List<Product> getBestSellers() =>
      _products.where((p) => p.isBestSeller).toList();

  static List<Product> getFlashSale() =>
      _products.where((p) => p.isFlashSale).toList();
}
